# Generated by Django 4.1.3 on 2022-11-29 02:38

from django.db import migrations, models
import django.db.models.deletion
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cnpj', django_cpf_cnpj.fields.CNPJField(max_length=18)),
                ('telefone', models.IntegerField(verbose_name='Telefone')),
                ('codigoPostal', models.IntegerField(verbose_name='CEP')),
                ('emailFornecedor', models.EmailField(max_length=100, verbose_name='Email')),
                ('fotoFornecedor', models.ImageField(null=True, upload_to='fornecedoresImg', verbose_name='Foto')),
            ],
        ),
        migrations.CreateModel(
            name='TipoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=30, verbose_name='Nome')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoproduto')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fornecedor')),
            ],
        ),
    ]
