# Generated by Django 4.1.3 on 2022-11-27 04:14

from django.db import migrations, models
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cnpj', django_cpf_cnpj.fields.CNPJField(max_length=18)),
                ('telefone', models.IntegerField(max_length=11, verbose_name='Telefone')),
                ('codigoPostal', models.IntegerField(max_length=8, verbose_name='CEP')),
                ('emailFornecedor', models.EmailField(max_length=100, verbose_name='Email')),
            ],
        ),
    ]
