# Generated by Django 4.1.3 on 2022-11-29 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('CRUD', 'Cadastrar,Ler,Atualizar,Apagar'), ('RU', 'Lerd,Atualizar')]},
        ),
    ]
