# Generated by Django 4.1.3 on 2022-12-06 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuario_options_remove_usuario_idade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('CD', 'Cadastrar,Apagar'), ('RU', 'Lerd,Atualizar')]},
        ),
        migrations.AddField(
            model_name='usuario',
            name='idade',
            field=models.IntegerField(default=21, verbose_name='Idade'),
            preserve_default=False,
        ),
    ]
