# Generated by Django 4.1.3 on 2022-11-29 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('CD', 'Cadastrar,Apagar'), ('RU', 'Lerd,Atualizar')]},
        ),
    ]
